package main

import "fmt"

func main() {
	// fmt.Println("Day 01 Part 1:", dayOnePartOne())
	// fmt.Println("Day 01 Part 2:", dayOnePartTwo())
	// fmt.Println("Day 02 Part 1:", dayTwoPartOne())
	// fmt.Println("Day 02 Part 2:", dayTwoPartTwo())
	// fmt.Println("Day 03 Part 1:", dayThreePartOne())
	// fmt.Println("Day 03 Part 2:", dayThreePartTwo())
	// fmt.Println("Day 04 Part 1:", dayFourPartOne())
	// fmt.Println("Day 04 Part 2:", dayFourPartTwo())
	// fmt.Println("Day 05 Part 1:", dayFivePartOne(false))
	// fmt.Println("Day 05 Part 2:", dayFivePartOne(true))
	// fmt.Println("Day 06 Part 1:", daySixPartOne())
	// fmt.Println("Day 06 Part 2:", daySixPartTwo())
	// fmt.Println("Day 07 Part 1:", daySevenPartOne(false))
	// fmt.Println("Day 07 Part 2:", daySevenPartOne(true))
	// fmt.Println("Day 08 Part 1:", dayEightPartOne())
	// fmt.Println("Day 08 Part 2:", dayEightPartTwo())
	// fmt.Println("Day 09 Part 1:", dayNinePartOne())
	// fmt.Println("Day 09 Part 2:", dayNinePartTwo())
	// fmt.Println("Day 10 Part 1:", dayTenPartOne())
	// fmt.Println("Day 10 Part 2:", dayTenPartTwo())
	// fmt.Println("Day 11 Part 1:", dayElevenPartOne())
	// fmt.Println("Day 11 Part 2:", dayEleventPartTwo())
	// fmt.Println("Day 12 Part 1:", dayTwelvePartOne())
	// fmt.Println("Day 12 Part 2:", dayTwelvePartTwo())
	// fmt.Println("Day 13 Part 1:", dayThirteenPartOne())
	// fmt.Println("Day 13 Part 2:")
	// dayThirteenPartTwo()
	// fmt.Println("Day 14 Part 1:", dayFourteenPartOne())
	// fmt.Println("Day 14 Part 2:", dayFourteenPartTwo())
	fmt.Println("Day 15 Part 1:", dayFifteenPartOne(false))
	fmt.Println("Day 15 Part 2:", dayFifteenPartOne(true))
}
